import "./globals.css";
import Header from "./components/header";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "MLDRASD App",
  description: "Generated by MLDRASD",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem("theme");if(t==="dark")document.documentElement.classList.add("dark")}catch(e){}})()`,
          }}
        />
      </head>
      <body
        className="antialiased min-h-screen"
      >
        <Header />
        {children}
        <Toaster
          position="top-center"
          reverseOrder={false}
          toastOptions={{
            style: {
              background: "var(--glass-bg)",
              color: "var(--text)",
              backdropFilter: "blur(16px)",
              border: "1px solid var(--glass-border)",
              borderRadius: "0.75rem",
            },
          }}
        />
      </body>
    </html>
  );
}
